#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import time


i = 0

try:
    while(True):
        print(str(i) + ' in stdout', flush=True)
        print(str(i) + ' in stderr', file=sys.stderr, flush=True)
        i += 1
        time.sleep(0.5)

        if i>5:
            break

except KeyboardInterrupt:
    sys.exit()
